#!/bin/bash

# Get the current Linux kernel version
kernel_version=$(uname -r)
echo "Current Linux kernel version: $kernel_version"

# Determine the kernel type (e.g., linux, linux-zen, linux-lts)
if [[ $kernel_version == *"zen"* ]]; then
    kernel_type="linux-zen"
elif [[ $kernel_version == *"lts"* ]]; then
    kernel_type="linux-lts"
else
    kernel_type="linux"
fi
echo "Kernel type: $kernel_type"

# Install Linux headers package
sudo pacman -S "${kernel_type}-headers" --noconfirm --needed
echo "Kernel type: $kernel_type"
